name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Check last execution time
        id: check-time
        run: |
          echo "::set-output name=updated-at::$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
        env:
          CACHE_NAME: CACHE_UPDATED_AT

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache-${{ env.CACHE_NAME }}-${{ github.sha }}

      - name: Run Hello World
        if: ${{ steps.check-time.outputs.updated-at == '' || steps.check-time.outputs.updated-at <= steps.restore-cache.outputs.CACHE_HIT }}
        run: |
          echo "Hello World"

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache-${{ env.CACHE_NAME }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-cache-${{ env.CACHE_NAME }}-

      - name: Cleanup cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache-${{ env.CACHE_NAME }}
          restore-keys: ${{ runner.os }}-cache-
