name: Get Last Commit Timestamp

on:
  push:
    branches:
      - main

jobs:
  get-commit-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Last Commit Timestamp
        id: last-commit
        run: |
          timestamp=$(git show -s --format=%aI origin/main)
          echo "::set-output name=commit-timestamp::${timestamp}"
      
      - name: Print Last Commit Timestamp
        run: |
          echo "Last Commit Timestamp: ${{ steps.last-commit.outputs.commit-timestamp }}"