name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Get last commit timestamp
        uses: actions/github-script@v6
        id: commit-details
        with:
          script: |
            const { repo, owner } = context.repo;
            const { data: commit } = await github.rest.repos.getCommit({
                owner,
                repo,
                ref: 'master'
            });
            core.setOutput("commit-timestamp", commit.commit.date);
      - name: Read Cache Value
        run: |
          cacheValue=$(cat "${{ steps.restore-cache.outputs.timestamp }}")
          echo "Cache Value: $cacheValue"

          