name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Set time
        id: check-time
        run: echo "name=updated-at::$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
        env:
          CACHE_NAME: CACHE_UPDATED_AT
          
      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: CACHE_UPDATED_AT

      - name: Read Cache Value
        run: |
          cacheValue=$(cat "${{ steps.restore-cache.outputs.cache-hit }}")
          echo "Cache Value: $cacheValue"

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: CACHE_UPDATED_AT

      - name: Run Hello World
        if: ${{ steps.check-time.outputs.updated-at == '' || steps.check-time.outputs.updated-at <= steps.restore-cache.outputs.CACHE_HIT }}
        run: |
          echo "Hello World"

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: CACHE_UPDATED_AT
          restore-keys: ${{ runner.os }}-cache-${{ env.CACHE_NAME }}-

      - name: Cleanup cache
        uses: actions/cache@v2
        with:
          path: ${{ runner.workspace }}
          key: ${{ runner.os }}-cache-${{ env.CACHE_NAME }}
          restore-keys: ${{ runner.os }}-cache-
